### ISSUE TITLE
pip install socketclusterclient failed

### ISSUE THREAD

**Issue by wilz5363** [sacOO7/socketcluster-client-python#13]
Got an error when trying to install this lib:

 ```
pip install socketclusterclient
Collecting socketclusterclient
  Using cached https://files.pythonhosted.org/packages/45/df/c1722d2117c07c931c719bc22d107f2a5ffff4404c6d74763c256ae5dc11/socketclusterclient-1.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-AeFzxf/socketclusterclient/setup.py", line 13, in <module>
        long_description=readme(),
      File "/tmp/pip-build-AeFzxf/socketclusterclient/setup.py", line 5, in readme
        with open('README.md') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-AeFzxf/socketclusterclient/
```

Python:2.7.x
OS: Rasberry Pi OS

**Comment by sacOO7** [comment]
Hi @wilz5363, will take a look into it and surely fix the issue 👍

**Comment by sacOO7** [comment]
Hi @wilz5363 , please try installing client now with same command, it should work :+1:

**Comment by wilz5363** [comment]
Superb!!!! thanks a lot!!
