### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by wilz5363** [sacOO7/socketcluster-client-python#18]
Tried the sample code and the client will randomly disconnected from the server socket

client error:
`ERROR:error from callback <bound method socket.on_message of <socketclusterclient.Socketcluster.socket object at 0xb66e1b50>>: [Errno 32] Broken pipe
  File "/usr/local/lib/python2.7/dist-packages/websocket/_app.py", line 320, in _callback
    callback(self, *args)
  File "/usr/local/lib/python2.7/dist-packages/socketclusterclient/Socketcluster.py", line 142, in on_message
    self.OnAuthentication(self, dataobject["isAuthenticated"])
  File "Raspicam/read_sensor.py", line 298, in onAuthentication
    readCounting(socket)
  File "Raspicam/read_sensor.py", line 258, in readCounting
    socket.emit("liveData", data)
  File "/usr/local/lib/python2.7/dist-packages/socketclusterclient/Socketcluster.py", line 38, in emit
    self.ws.send(json.dumps(emitobject, sort_keys=True))
  File "/usr/local/lib/python2.7/dist-packages/websocket/_app.py", line 151, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 240, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 265, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 430, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python2.7/dist-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)`

From the server, i used socket cluster framework `npm install -g socketcluster`,

Server error log:
`1539082127010 - Origin: Worker (PID 7372)
   [Warning] SocketProtocolError: Client pong timed out
    at SCServerSocket._onSCClose (D:\Projects\NodeServer\NodeCluster\node_modules\socketcluster-server\scserversocket.js:249:17)
    at Timeout.<anonymous> (D:\Projects\NodeServer\NodeCluster\node_modules\socketcluster-server\scserversocket.js:194:10)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)`

Client and server they are connected thru LAN. So, i'm not sure what went wrong here.
Let me know if you need extra info.

**Comment by wilz5363** [comment]
in `onAuthentication`, i have a custom function with loop. Instead of looping and time.sleep in that, i removed them and put them in the `onAuthentication` function.

Eg:
```
def onAuthentication(socket, isauthenticated):
    while True:
        readCounting(socket)
        time.sleep(2)
```

**Comment by sacOO7** [comment]
Why are you exactly applying sleep? You can start that readCounting function in different thread. If you don't have any performance problem with above approach, then it's ok.
